### DISCUSSION TITLE
RomM Library refactor (to be compatible with template/device logic)

### DISCUSSION THREAD

**Discussion by XargonWan** [rommapp/romm#294] [Ideas]
Here is an example of how RomM can handle a library file to be compatible with the template/device logic.

```
# Sticking to the Batocera standard
# https://wiki.batocera.org/systems

library:
  id: library
  name: Library
  template_version: 3.0
  gamelist_file: null
  systems:

    - arcade:
        merged:
            - mame
            - fbneo

    - mame:
        name: MAME
        manufacturer: MAME
        system_folders:
            - mame
        extensions:
            - zip
            - 7z

    - fbneo:
        name: FinalBurn Neo
        manufacturer: FinalBurn Neo
        system_folders:
            - fbneo
            - finalburn
        extensions:
            - zip
            - 7z

    - daphne:
        name: LaserDisc
        manufacturer: DAPHNE
        system_folders:
            - daphne
            - laserdisc
        extensions:
            - daphne
            - squashfs

    - model1:
        name: Model 1
        manufacturer: SEGA
        release: 1992
        system_folders:
            - model1
        extensions:
            - zip
            - 7z

    - model2:
        name: Model 2
        manufacturer: SEGA
        release: 1994
        system_folders:
            - model2
        extensions:
            - zip

    - model3:
        name: Model 3
        manufacturer: SEGA
        release: 1996
        system_folders:
            - model3
        extensions:
            - zip 

    - naomi:
        name: SEGA Naomi
        manufacturer: SEGA
        release: 1998
        system_folders:
            - naomi
        extensions:
            - lst
            - bin
            - dat
            - zip
            - 7z

    - naomi2:
        name: SEGA Naomi
        manufacturer: SEGA
        release: 2000
        system_folders:
            - naomi2
        extensions:
            - zip
            - 7z

    - triforce:
        name: Triforce
        manufacturer: Namco, Sega and Nintendo
        release: 2002
        system_folders:
            - triforce
        extensions:
            - gcm
            - iso
            - gcz
            - ciso
            - wbfs
            - elf
            - dol
            - m3u

    - atomiswave:
        name: Sammy Atomiswave
        manufacturer: Sammy
        system_folders:
            - atomiswave
        extensions:
            - lst
            - bin
            - dat
            - zip
            - 7z

    - channelf:
        name: Channel F
        manufacturer: Fairchild
        system_folders:
            - channelf
        extensions:
            - bin
            - fc
            - zip
            - 7z

    - atari2600:
        name: Atari 2600
        manufacturer: Atari
        system_folders:
            - atari2600
        extensions:
            - a26
            - bin
            - zip
            - 7z

    - odyssey:
        name: Odyssey²
        manufacturer: Magnavox
        release: 1978
        system_folders:
            - odyssey
        extensions:
            - bin
            - zip
            - 7z

    - astrocde:
        name: Astrocade
        manufacturer: Bally
        release: 1978
        system_folders:
            - astrocde
        extensions:
            - bin
            - zip
            - 7z

    - apfm1000:
        name: APF-MP1000
        manufacturer: APF Electronics
        release: 1978
        system_folders:
            - apfm1000
        extensions:
            - bin
            - zip
            - 7z

    - intellivision:
        name: Intellivision
        manufacturer: Mattel
        system_folders:
            - intellivision
        extensions:
            - int
            - bin
            - rom
            - zip
            - 7z

    - atari5200:
        name: Atari 5200
        manufacturer: Atari
        system_folders:
            - atari5200
        extensions:
            - rom
            - xfd
            - atr
            - atx
            - cdm
            - cas
            - car
            - bin
            - a52
            - xex
            - zip
            - 7z

    - colecovision:
        name: ColecoVision
        manufacturer: Coleco
        system_folders:
            - coleco
            - colecovision
        extensions:
            - bin
            - col
            - rom
            - zip
            - 7z

    - advision:
        name: Adventure Vision
        manufacturer: Entex
        system_folders:
            - advision
        extensions:
            - bin
            - zip
            - 7z

    - vectrex:
        name: Vectrex
        manufacturer: Milton Bradley
        system_folders:
            - vectrex
        extensions:
            - bin
            - gam
            - vec
            - zip
            - 7z

    - cpc:
        name: Color Personal Computer (CPC)
        manufacturer: Amstrad
        system_folders:
            - amstradcpc
            - cpc
        extensions:
            - dsk
            - sna
            - tap
            - cdt
            - voc
            - m3u
            - zip
            - 7z

    - atari7800:
        name: Atari 7800
        manufacturer: Atari
        system_folders:
            - atari7800
        extensions:
            - a78
            - bin
            - zip
            - 7z

    - atarijaguar:
        name: Atari Jaguar
        manufacturer: Atari
        system_folders:
            - atarijaguar
            - jaguar
        extensions:
            - j64
            - jag

    - jaguarcd:
        name: Jaguar CD
        manufacturer: Atari
        system_folders:
            - jaguarcd
        extensions:
            - iso
            - cue
            - chd

    - atarilynx:
        name: Atari Lynx
        manufacturer: Atari
        system_folders:
            - atarilynx
            - lynx
        extensions:
            - lnx
            - o
            - zip
            - 7z

    - sufami:
        name: SuFami Turbo
        manufacturer: Bandai
        system_folders:
            - sufami
        extensions:
            - st
            - zip
            - 7z

    - ws:
        name: Wonderswan
        manufacturer: Bandai
        system_folders:
            - wonderswan
            - ws
        extensions:
            - ws
            - zip
            - 7z

    - wsc:
        name: Wonderswan Color
        manufacturer: Bandai
        system_folders:
            - wonderswancolor
            - wsc
        extensions:
            - wsc
            - zip
            - 7z

    - pv1000:
        name: PV-1000
        manufacturer: Casio
        system_folders:
            - pv1000
        extensions:
            - bin
            - zip
            - 7z

    - amigacd32:
        name: Amiga CD32
        manufacturer: Commodore
        system_folders:
            - amigacd32
        extensions:
            - iso
            - cue
            - chd
            - lha

    - gpc:
        name: Game Pocket Computer
        manufacturer: Epoch
        system_folders:
            - gamepocketcomputer
            - gpc
        extensions:
            - bin
            - zip
            - 7z

    - gamemaster:
        name: Game Master
        manufacturer: Hartung
        system_folders:
            - gamemaster
        extensions:
            - bin
            - zip
            - 7z

    - pcengine:
        name: PC Engine
        name_alt: {(us,TurboGrafx 16)}
        manufacturer: NEC
        system_folders:
            - pcengine
            - pce
            - turbografx16
        extensions:
            - pce
            - bin
            - zip
            - 7z

    - pcenginecd:
        name: PC Engine CD
        name_alt: ({(us,TurboGrafx-CD)})
        manufacturer: NEC
        system_folders:
            - pcenginecd
            - pcecd
        extensions:
            - cue
            - ccd
            - chd
            - bin
            - m3u
            - pce
            - iso
            - img

    - supergrafx:
        name: PC Engine SuperGrafx
        manufacturer: NEC
        system_folders:
            - sgfx
            - supergrafx
            - pcesgfx
        extensions:
            - pce
            - sgx
            - cue
            - ccd
            - chd
            - zip
            - 7z

    - pcfx:
        name: PC-FX
        manufacturer: NEC
        system_folders:
            - pcfx
        extensions:
            - chd
            - cue
            - ccd
            - toc

    - fmtowns:
        name: FM-TOWNS
        manufacturer: Fujitsu
        system_folders:
            - fmtowns
        extensions:
            - iso
            - cue
            - fds
            - zip
            - 7z

    - gamate:
        name: Gamate
        manufacturer: Bit Corp
        system_folders:
            - gamate
        extensions:
            - bin
            - zip
            - 7z

    - gw:
        name: Game and Watch
        manufacturer: Nintendo
        system_folders:
            - gw
            - gameandwatch
        extensions:
            - mgw
            - zip
            - 7z

    - gb:
        name: Game Boy
        manufacturer: Nintendo
        system_folders:
            - gameboy
        extensions:
            - gb
            - gbc
            - cgb
            - sgb
            - zip
            - 7z

    - sgb:
        name: Super Game Boy
        manufacturer: Nintendo
        system_folders:
            - sgb
        extensions:
            - gb
            - gbc
            - zip
            - 7z

    - gbc:
        name: Game Boy Color
        manufacturer: Nintendo
        system_folders:
            - gameboycolor
            - gbc
        extensions:
            - gbc
            - zip
            - 7z

    - pokemini:
        name: Pokemon Mini
        manufacturer: Nintendo
        system_folders:
            - pokemini
        extensions:
            - min

    - gba:
        name: Game Boy Advance
        manufacturer: Nintendo
        system_folders:
            - gba
        extensions:
            - gba
            - agb
            - zip
            - 7z

    - nds:
        name: Nintendo DS
        manufacturer: Nintendo
        system_folders:
            - nds
        extensions:
            - nds
            - wad

    - n3ds:
        name: Nintendo 3DS
        manufacturer: Nintendo
        dlc: true
        patches: true
        system_folders:
            - n3ds
        extensions:
            - 3ds
            - cia

    - famicom:
        name: Famicom
        manufacturer: Nintendo
        system_folders:
            - famicom
            - fc
        extensions:
            - nes
            - unif
            - unf
            - zip
            - 7z

    - nes:
        name: Nintendo Entertainment System
        manufacturer: Nintendo
        system_folders:
            - nes
        extensions:
            - nes
            - zip
            - 7z

    - sfc:
        name: Super Famicom
        manufacturer: Nintendo
        system_folders:
            - sfc
        extensions:
            - sfc
            - zip
            - 7z

    - fds:
        name: Super Famicom Disk System
        manufacturer: Nintendo
        system_folders:
            - fds
        extensions:
            - fds
            - zip
            - 7z

    - snes:
        name: Super Nintendo Entertainment System
        manufacturer: Nintendo
        system_folders:
            - snes
        extensions:
            - sfc
            - zip
            - 7z

    - vb:
        name: Virtual Boy
        manufacturer: Nintendo
        system_folders:
            - vb
            - virtualboy
        extensions:
            - vb
            - zip
            - 7z

    - n64:
        name: Nintendo 64
        manufacturer: Nintendo
        system_folders:
            - n64
        extensions:
            - n64
            - z64
            - v64
            - zip
            - 7z

    - gc:
        name: Game Cube
        manufacturer: Nintendo
        system_folders:
            - gc
        extensions:
            - rvz

    - wii:
        name: Nintendo Wii
        manufacturer: Nintendo
        dlc: true
        patches: true
        system_folders:
            - wii
        extensions:
            - rvz
            - wad

    - wiiu:
        name: Nintendo Wii U
        manufacturer: Nintendo
        dlc: true
        patches: true
        system_folders:
            - wiiu
        extensions:
            - wua
    
    - switch:
        name: Switch
        manufacturer: Nintendo
        dlc: true
        patches: true
        system_folders:
            - switch
        extensions:
            - xci
            - nsp

    - sg1000:
        name: SG-1000
        manufacturer: SEGA
        system_folders:
            - sg1000
        extensions:
            - sms
            - gg
            - sg
            - mv
            - bin
            - rom
   
    - mastersystem:
        name: Master System
        manifacturer: SEGA
        name_alt: Mark III
        release: ({
            (jp,18-10-1987),
            (fr,01-09-1987),
            (us,01-10-1986),
            (uk,01-08-1987),
            (br,01-12-1990),
            (au,01-01-1986),
            (de,01-10-1986),
            (it,01-11-1986),
            (kr,01-04-1989)
            })
        system_folders:
          - mastersystem
          - ms
          - sms
        extensions:
          - sms
          - zip
          - 7z

    - megadrive:
        name: Megadrive
        manifacturer: SEGA
        name_us: Genesis
        release: ({
            (jp,29-10-1988),
            (eu,01-11-1990),
            (us,14-07-1989),
            (uk,14-08-1990),
            (br,01-12-1990)
            })
        system_folders:
          - megadrive
          - genesis
        extensions:
          - 68k
          - mdx
          - md
          - sgd
          - smd
          - gen
          - bin
          - zip
          - 7z

    - megadrivejp:
        name: Megadrive (Japan)
        manifacturer: SEGA
        name_us: Genesis
        release: ({(jp,29-10-1988)})
        system_folders:
          - megadrivejp
        extensions:
          - 68k
          - mdx
          - md
          - sgd
          - smd
          - gen
          - bin
          - zip
          - 7z

    - 32x:
        name: Mega Drive 32X
        manufacturer: SEGA
        system_folders:
            - 32x
        extensions:
        - bin
        - gen
        - smd
        - md
        - 32x
        - cue
        - iso
        - sms
        - 68k
        - chd
    
    - dreamcast:
        name: Dreamcast
        manifacturer: SEGA
        system_folders:
            - dreamcast
            - dc
        extensions:
            - cdi
            - gdi
            - chd
            - cue
            - bin
            - elf
            - zip
            - 7z
            - lst
            - dat
            - m3u

    - saturn:
        name: Saturn
        manifacturer: SEGA
        system_folders:
            - saturn
        extensions:
            - cue
            - toc
            - m3u
            - ccd
            - chd

    - gg:
        name: Game Gear
        manufacturer: SEGA
        system_folders:
            - gamegear
            - gg
        extensions:
            - gg
            - zip
            - 7z

    - msx:
        name: MSX
        manufacturer: Microsoft
        system_folders:
            - msx
        extensions:
            - rom
            - dsk
            - zip
            - 7z

    - dos:
        name: MS-DOS
        manufacturer: Microsoft
        system_folders:
            - dos
            - msdos
            - pc
        extensions:
            - dosz
    
    - xbox:
        name: Xbox
        manufacturer: Microsoft
        system_folders:
            - xbox
        extensions:
            - xiso.iso
            - iso
            - xiso

    - xbox360:
        name: Xbox 360
        manufacturer: Microsoft
        system_folders:
            - xbox360
        extensions:
            - xex


    - neogeo:
        name: NEO•GEO MVS
        manufacturer: SNK
        system_folders:
            - neogeo
        extensions:
            - rom
            - zip
            - 7z

    - ngp:
        name: Neo Geo Pocket
        manufacturer: SNK
        system_folders:
            - ngp
        extensions:
            - ngp
            - ngc
            - zip
            - 7z

    - ngpc:
        name: Neo Geo Pocket Color
        manufacturer: SNK
        system_folders:
            - ngpc
        extensions:
            - ngc
            - zip
            - 7z

    - zxspectrum:
        name: ZX Spectrum
        manufacturer: Sinclair
        system_folders:
            - zxspectrum
        extensions:
            - z80
            - sna
            - zx
            - zip
            - 7z

    - psx:
        name: PlayStation
        manufacturer: Sony
        system_folders:
            - psx
            - ps
            - m3u
        extensions:
            - chd
            - bin
            - iso
            - zip
            - 7z

    - ps2:
        name: PlayStation 2
        manufacturer: Sony
        system_folders:
            - ps2
        extensions:
            - chd
            - bin
            - iso
            - zip
            - 7z

    - ps3:
        name: PlayStation 3
        manufacturer: Sony
        system_folders:
            - ps3
        extensions:
            - sfb
            - pkg

    - psp:
        name: PlayStation Portable
        manufacturer: Sony
        system_folders:
            - psp
        extensions:
            - iso
            - cso

    - psvita:
        name: PS Vita
        manufacturer: Sony
        system_folders:
            - psvita
        extensions:
            - pkg

    - pico8:
        name: PICO-8
        manufacturer: Lexaloffle
        system_folders:
            - pico8
            - pico-8
        extensions:
            - p8
            - png
            - m3u

    - tic80:
        name: TIC-80
        manufacturer: nesbox
        system_folders:
            - tic80
            - tic
        extensions:
            - tic

    - uzebox:
        name: Uzebox
        system_folders:
            - uzebox
        extensions:
            - uze
    
    - wasm4:
        name: WASM4
        system_folders:
            - wasm4
        extensions:
            - wasm
```
