### ISSUE TITLE
[Bug] Unable to access romm system (500: Internal Server Error & 403: User not found)

### ISSUE THREAD

**Issue by NicksGhost** [rommapp/romm#1015]
**RomM version**
3.3.0

**Describe the bug**
After the deployment is completed using docker-compose, accessing the romm homepage console shows `GET http://192.168.3.2:7990/api/heartbeat 500 (Internal Server Error)`; in the docker log it is `fastapi.exceptions.HTTPException: 403: User not found`, and it is also impossible to log in to the romm system.

```yaml
version: '3.3'

services:
  romm_server:
    container_name: romm_server
    image: rommapp/romm:latest
    restart: unless-stopped
    depends_on:
      - romm_database
    ports:
      - 7990:8080
    environment:
      - DB_HOST=romm_database
      - DB_NAME=romm
      - DB_USER=romm-user
      - DB_PASSWD=[xxxxxxxx]
      - ROMM_AUTH_SECRET_KEY=[xxxxxxxx]
      - MOBYGAMES_API_KEY=[xxxxxxxx]
      - STEAMGRIDDB_API_KEY=[xxxxxxxx]
    volumes:
      - /volume1/docker/romm/assets:/romm/assets
      - /volume1/docker/romm/config:/romm/config
      - /volume1/docker/romm/library:/romm/library
      - /volume1/docker/romm/resources:/romm/resources
      - /volume1/docker/romm/data/redis:/redis-data

  romm_database:
    container_name: romm_database
    image: linuxserver/mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=[xxxxxxxx]
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=[xxxxxxxx]
    volumes:
      - /volume1/docker/romm/data/mariadb:/var/lib/mysql
```

**To Reproduce**

1. Run docker-compose.yml
2. Container service loading completed
3. Open romm's web ui

**Screenshots**

- **Docker console log:**
![1](https://github.com/user-attachments/assets/d6e3c068-185d-4c05-beee-2a8cb3a10382)

- **Browser console log:**
![2](https://github.com/user-attachments/assets/df938091-c733-4f4b-b6b6-de3695d7773c)
![3](https://github.com/user-attachments/assets/40fdc83f-1629-4a61-a0ea-2b320a11daa9)

**Server**

- OS: Synology DSM
- Version: 6.2.2

**Desktop**

- OS: Windwos 11
- Browser: Microsoft Edge
- Version: 23H2
