### ISSUE TITLE
[Bug] Access denied for user 'romm-user'@'IP' (Using Password: yes)

### ISSUE THREAD

**Issue by prvsmrtsltppr7** [rommapp/romm#1053]
**RomM version**
latest

**Describe the bug**
When loading docker, the container constantly restarts and this error appearing in the logs. 

**Expected behavior**
The web interface doesn't load as the container throws an error. 

```
volumes:
  mysql_data:
  romm_resources:
  romm_redis_data:

services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    environment:
      - DB_HOST=romm-db
      - DB_NAME=romm 
      - DB_USER=romm-user
      - DB_PASSWD= PW
      - ROMM_AUTH_SECRET_KEY= KEY
      - IGDB_CLIENT_ID= 
      - IGDB_CLIENT_SECRET= 
      - MOBYGAMES_API_KEY= KEY
      - STEAMGRIDDB_API_KEY 
    volumes:
      - romm_resources:/romm/resources 
      - romm_redis_data:/redis-data 
      - /home/games/library:/romm/library 
      - /home/games/assets:/romm/assets 
      - /home/games/config:/romm/config
    ports:
      - 80:8080
    depends_on:
      - romm-db

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD= PW
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD= PW
    volumes:
      - mysql_data:/var/lib/mysql
```

**Desktop (please complete the following information):**

Docker container running on Proxmox LXC
