### ISSUE TITLE
[Bug] Unable to scrape IGDB

### ISSUE THREAD

**Issue by NicksGhost** [rommapp/romm#1094]
**RomM version**
3.4.0

**Describe the bug**
There seems to be an anomaly in scraping IGDB metadata when scanning roms? The scraping function does not work properly, and an error message appears after waiting for a while after clicking the scan button.

```yaml
version: '3.3'

services:
  romm_server:
    container_name: romm_server
    image: rommapp/romm:latest
    restart: unless-stopped
    depends_on:
      - romm_database
    ports:
      - 7990:8080
    environment:
      - DB_HOST=romm_database
      - DB_NAME=romm
      - DB_USER=romm-user
      - DB_PASSWD=[xxxxxxxx]
      - ROMM_AUTH_SECRET_KEY=[xxxxxxxx]
      - IGDB_CLIENT_ID=[xxxxxxxx]
      - IGDB_CLIENT_SECRET=[xxxxxxxx]
      - MOBYGAMES_API_KEY=[xxxxxxxx]
      - STEAMGRIDDB_API_KEY=[xxxxxxxx]
    volumes:
      - /volume1/docker/romm/assets:/romm/assets
      - /volume1/docker/romm/config:/romm/config
      - /volume1/docker/romm/library:/romm/library
      - /volume1/docker/romm/resources:/romm/resources
      - /volume1/docker/romm/data/redis:/redis-data

  romm_database:
    container_name: romm_database
    image: linuxserver/mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=[xxxxxxxx]
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=[xxxxxxxx]
    volumes:
      - /volume1/docker/romm/data/mariadb:/var/lib/mysql
```

**To Reproduce**

1. Run docker-compose.yml
2. Container service loading completed
3. Open romm's web ui
4. Click scan button
5. See error

**Screenshots**

- **Seems to be abnormal:**
![2](https://github.com/user-attachments/assets/9abc9ba0-4fea-4512-bd52-d708f4f72fd9)
![1](https://github.com/user-attachments/assets/3970eb65-1b31-4b13-9a69-5955e257a604)

- **Access to IGDB should be normal:**
![3](https://github.com/user-attachments/assets/e082db09-1f77-403c-ba53-5766ea6f36e3)

**Server**

- OS: Synology DSM
- Version: 7.2

**Desktop**

- OS: Windows 11
- Browser: Microsoft Edge
- Version: 23H2

**Comment by gantoine** [comment]
Strange, following the code you should see `Twitch token fetched!` somewhere in the logs right after. All other branches are other error logs...

**Comment by NicksGhost** [comment]
> Strange, following the code you should see `Twitch token fetched!` somewhere in the logs right after. All other branches are other error logs...

I see that it seems that other people have had similar problems, but here I don't see the log information of the acquisition success, and the scraping operation also fails.

**Comment by gantoine** [comment]
It is possible your container has no access to the internet?

**Comment by NicksGhost** [comment]
> It is possible your container has no access to the internet?

I think it is unlikely, because if you don't choose IGDB as the metadata source, you can get scraped metadata from MobyGames.

**Comment by gantoine** [comment]
Oh interesting! Not sure what's going on here, it's like your IGDB request is being swallowed by the api and never gets updated.

**Comment by NicksGhost** [comment]
> Oh interesting! Not sure what's going on here, it's like your IGDB request is being swallowed by the api and never gets updated.

I am confused. Now I am considering whether there is a problem with IGDB's API settings or authorization keys, but I use HTTP tools to access and test to obtain tokens, and I can also obtain metadata normally using MobyGames alone. I am currently unable to determine where the problem comes from. Do you have any other solutions?

**Comment by NicksGhost** [comment]
> Oh interesting! Not sure what's going on here, it's like your IGDB request is being swallowed by the api and never gets updated.

Hi, I seem to have solved this problem, but I still don't know what caused it. I first deployed mariadb independently, and then deployed romm independently. After waiting for the project to start, I was able to obtain metadata normally. Why is network connection and acquisition related to the database?

```yaml
version: '3.3'

services:
  mariadb:
    container_name: mariadb_server
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=[xxxxxxxx]
      - MYSQL_ROOT_PASSWORD=[xxxxxxxx]
    volumes:
      - /volume1/docker/database/mariadb/data:/var/lib/mysql
      - /volume1/docker/database/mariadb/log:/var/log/mysql

  phpmyadmin:
    container_name: phpmyadmin_server
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 3080:80
    environment:
      - PMA_HOST=mariadb_server
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb
```
```yaml
version: '3.3'

services:
  romm:
    container_name: romm_server
    image: rommapp/romm:latest
    restart: unless-stopped
    ports:
      - 7990:8080
    environment:
      - DB_HOST=mariadb_server
      - DB_NAME=romm
      - DB_USER=romm-user
      - DB_PASSWD=[xxxxxxxx]
      - ROMM_AUTH_SECRET_KEY=[xxxxxxxx]
      - IGDB_CLIENT_ID=[xxxxxxxx]
      - IGDB_CLIENT_SECRET=[xxxxxxxx]
      - MOBYGAMES_API_KEY=[xxxxxxxx]
      - STEAMGRIDDB_API_KEY=[xxxxxxxx]
    volumes:
      - /volume1/docker/romm/assets:/romm/assets
      - /volume1/docker/romm/config:/romm/config
      - /volume1/docker/romm/cache:/redis-data
      - /volume1/docker/romm/resources:/romm/resources
      - /volume2/games/Roms:/romm/library

networks:
  default:
    external:
      name: database_default
```
