### ISSUE TITLE
[Bug] 404 when attempting to download any file

### ISSUE THREAD

**Issue by DarkVirtue** [rommapp/romm#1466]
**RomM version**
3.7.0

**Describe the bug**
When attempting to download a ROM or any related files, I get a `404 Page not found` error from RomM. This occurs even for games I can play in the browser.

**To Reproduce**

1. Navigate to a game's page.
2. Click the download icon under the cover image.
3. 404 error.

**Expected behavior**
The download should start.

**Screenshots**
![Screenshot_20250110_122224](https://github.com/user-attachments/assets/dce07d4c-fd43-4f9a-a248-2d2779b92683)

**Desktop (please complete the following information):**
- OS: Fedora 41
- Browser: Firefox 134.0

**Additional context**
This is happening with every game in my library, even those I've downloaded before and those I've just played. I don't know when this issue started. Re-scanning the platform detects no changes.

<details>
<summary> Logs, compose, and env</summary>

```
romm-1  | INFO:   [nginx][2025-01-10 20:24:37]  10.11.1.1 - - "GET /ws/socket.io/?EIO=4&transport=websocket HTTP/1.1" 101 193 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0" rt=164.531 uct="0.000" uht="0.016" urt="164.531"
romm-1  | [2025-01-10 20:24:37 +0000] [19] [INFO] connection closed
romm-1  | 134.79.165.115:0 - "GET /api/heartbeat HTTP/1.0" 200
romm-1  | INFO:   [nginx][2025-01-10 20:24:37]  10.11.1.1 - - "GET /api/heartbeat HTTP/1.1" 200 868 "https://[REDACTED]/api/roms/3136/content/ActRaiser%20(reg-USA).zip" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0" rt=0.110 uct="0.000" uht="0.109" urt="0.109"
romm-1  | 134.79.165.115:0 - "GET /api/users/me HTTP/1.0" 200
romm-1  | INFO:   [nginx][2025-01-10 20:24:37]  10.11.1.1 - - "GET /api/users/me HTTP/1.1" 200 569 "https://[REDACTED]/api/roms/3136/content/ActRaiser%20(reg-USA).zip" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0" rt=0.019 uct="0.000" uht="0.019" urt="0.019"
romm-1  | 134.79.165.115:0 - "GET /api/config HTTP/1.0" 200
romm-1  | INFO:   [nginx][2025-01-10 20:24:37]  10.11.1.1 - - "GET /api/config HTTP/1.1" 200 720 "https://[REDACTED]/api/roms/3136/content/ActRaiser%20(reg-USA).zip" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0" rt=0.033 uct="0.000" uht="0.032" urt="0.033"
romm-1  | [2025-01-10 20:24:38 +0000] [20] [INFO] ('134.79.165.115', 0) - "WebSocket /ws/socket.io/?EIO=4&transport=websocket" [accepted]
romm-1  | [2025-01-10 20:24:38 +0000] [20] [INFO] connection open
romm-1  | INFO:   [nginx][2025-01-10 20:24:38]  10.11.1.1 - - "GET /assets/romm/assets/users/557365723a36/profile/Bahamut_Avy.png?ts=2025-01-10T20:24:37 HTTP/1.1" 200 217130 "https://[REDACTED]/api/roms/3136/content/ActRaiser%20(reg-USA).zip" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0" rt=0.000 uct="-" uht="-" urt="-"
romm-1  | 134.79.165.115:0 - "GET /api/platforms HTTP/1.0" 200
romm-1  | INFO:   [nginx][2025-01-10 20:24:38]  10.11.1.1 - - "GET /sw.js HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0" rt=0.000 uct="-" uht="-" urt="-"
romm-1  | INFO:   [nginx][2025-01-10 20:24:38]  10.11.1.1 - - "GET /api/platforms HTTP/1.1" 200 16217 "https://[REDACTED]/api/roms/3136/content/ActRaiser%20(reg-USA).zip" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0" rt=0.208 uct="0.000" uht="0.207" urt="0.208"
romm-1  | 134.79.165.115:0 - "GET /api/collections HTTP/1.0" 200
romm-1  | INFO:   [nginx][2025-01-10 20:24:38]  10.11.1.1 - - "GET /api/collections HTTP/1.1" 200 2 "https://[REDACTED]/api/roms/3136/content/ActRaiser%20(reg-USA).zip" "Mozilla/5.0 (X11; Linux x86_64; rv:134.0) Gecko/20100101 Firefox/134.0" rt=0.023 uct="0.000" uht="0.022" urt="0.023"
```

`compose.yml`
```
services:
  romm:
    image: rommapp/romm:latest
    user: "1001:1001"
    env_file:
       - .env
    volumes:
      - '/library/roms/roms_files:/romm/library/roms:ro'
      - '/library/roms/roms_bios:/romm/library/bios:ro'
      - '/containers/roms/romm/resources:/romm/resources'
      - '/containers/roms/romm/config:/romm/config'
      - '/containers/roms/romm/assets:/romm/assets'
    ports:
      - 127.0.0.1:8084:8080
    depends_on:
      - database
      - keystore
    restart: "unless-stopped"

  database:
    image: mariadb:lts
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    command: '--log-bin'
    volumes:
      - /containers/roms/db:/var/lib/mysql

  keystore:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    restart: unless-stopped
    volumes:
      - keystore-data:/data

volumes:
  keystore-data:
```

`.env`
```
DB_HOST=database
DB_PORT=3306
DB_USER=romm
DB_NAME=romm
DB_PASSWD=[[ROMM_DB_PASS]]
DISABLE_CSRF_PROTECTION=true
REDIS_HOST=keystore
REDIS_PORT=6379
IGDB_CLIENT_ID=[[IGDB_CLIENT_ID]]
IGDB_CLIENT_SECRET=[[IGDB_CLIENT_SECRET]]
STEAMGRIDDB_API_KEY=[[STEAMGRID_API_KEY]]
MOBYGAMES_API_KEY=[[MOBYGAMES_API_KEY]]
ROMM_AUTH_SECRET_KEY=[[ROMM_AUTH_SECRET]]
ROMM_AUTH_USERNAME=admin
ROMM_AUTH_PASSWORD=[[ROMM_AUTH_PASS]]
OIDC_ENABLED=true
OIDC_PROVIDER=authentik
OIDC_CLIENT_ID=[[ROMM_OIDC_CLIENT_ID]]
OIDC_CLIENT_SECRET=[[ROMM_OIDC_CLIENT_SECRET]]
OIDC_REDIRECT_URI=[[ROM_DOMAIN]]/api/oauth/openid
OIDC_SERVER_APPLICATION_URL=[[AUTH_DOMAIN]]/application/o/romm-application
DISABLE_USERPASS_LOGIN=true
ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=false
ENABLE_SCHEDULED_RESCAN=false
ENABLE_SCHEDULED_SWITCH_TITLEDB=false
ENABLE_SCHEDULED_UPDATE_MAME_XML=false
```
</details>
