### ISSUE TITLE
[Bug] Default controller input not corresponding to standard xinput layout

### ISSUE THREAD

**Issue by wonx** [rommapp/romm#1549]
**RomM version**
3.7.2

**Describe the bug**
When using a controller with RomM, the default mapping is not what you would expect for the four face buttons. 
For instance, if playing Playstations games, circle and X are switched, and square and triangle are switched. The dpad and shoulder buttons seem to be correctly mapped, though.

**To Reproduce**
Just pair a controller (via xinput), and start a rom.

**Expected behavior**
I'd map by default controls to those most similar to current xbox or playstation controllers. 

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Firefox 
- Version 143.0.2

**Additional context**
It seems to be consistent across cores, I just tested it in PSX and SNES.

**Comment by nadiaholmquist** [comment]
This is also a problem when using a PlayStation 5 controller in Firefox on Linux.

I've only tested the SNES core so far, but with it the face buttons end up being mapped as if the emulated controller was an Xbox controller, i.e.:
```
  Y       Triangle
X   B = Square Circle
  A         Cross
```
But the expected mapping would be:
```
  X       Triangle
Y   A = Square Circle
  B         Cross
```

This makes games harder to play as for example Mario doesn't jump when you press the "south" face button (Cross (SNES B) in this case) but rather would do a spin jump.

This is likely wrong because libreto uses the Nintendo-style face button layout for its button mapping for cores (A = right/east face button), but you might have assumed the labels were supposed to match an Xbox controller.

Edit: Also tested a Nintendo Switch Pro Controller and a Nintendo Switch SNES controller, same problem.

**Comment by wonx** [comment]
Hi

now that request issue #1250 has been implemented, I'd like to change the controls to swap A/B and X/Y, so controllers in Windows have the correct assignments. I tried manually adding a section like this in the `config.yml` file, but I don't see the control mappings taking any effect:

```
emulatorjs:
  settings:
    default:
      fps: show
  controls: # https://emulatorjs.org/docs4devs/control-mapping/
    default: # These settings apply to all cores
      0: # Player 1
        0: # B
          value1: x
          value2: BUTTON_2
```

(I also tried setting all the buttons, as indicated in https://emulatorjs.org/docs4devs/control-mapping/ )

Could you give us a sample configuration that we can use, so at least I'm sure of the format it should be?

Thanks in advance.

**Comment by sliekens** [comment]
@wonx I don't think you can use `default` underneath `controls`, it expects the name of a core.

This worked for me, for PSX:

``` yaml copy
# EmulatorJS per-core options
emulatorjs:
  controls: # https://emulatorjs.org/docs4devs/control-mapping/
    # Name of the core
    pcsx_rearmed:
      # Player 1
      0:
        # B (Cross)
        0:
          value2: BUTTON_1
        # Y (Square)
        1:
          value2: BUTTON_3
        # SELECT
        2:
          value2: SELECT
        # START
        3:
          value2: START
        # UP
        4:
          value2: DPAD_UP
        # DOWN
        5:
          value2: DPAD_DOWN
        # LEFT
        6:
          value2: DPAD_LEFT
        # RIGHT
        7:
          value2: DPAD_RIGHT
        # A (Circle)
        8:
          value2: BUTTON_2
        # X (Triangle)
        9:
          value2: BUTTON_4
        # L1
        10:
          value2: LEFT_TOP_SHOULDER
        # R1
        11:
          value2: RIGHT_TOP_SHOULDER
        # L2
        12:
          value2: LEFT_BOTTOM_SHOULDER
        # R2
        13:
          value2: RIGHT_BOTTOM_SHOULDER
        # L3
        14:
          value2: LEFT_STICK
        # R3
        15:
          value2: RIGHT_STICK
        # L STICK RIGHT
        16:
          value2: LEFT_STICK_X:+1
        # L STICK LEFT
        17:
          value2: LEFT_STICK_X:-1
        # L STICK DOWN
        18:
          value2: LEFT_STICK_Y:+1
        # L STICK UP
        19:
          value2: LEFT_STICK_Y:-1
        # R STICK RIGHT
        20:
          value2: RIGHT_STICK_X:+1
        # R STICK LEFT
        21:
          value2: RIGHT_STICK_X:-1
        # R STICK DOWN
        22:
          value2: RIGHT_STICK_Y:+1
        # R STICK UP
        23:
          value2: RIGHT_STICK_Y:-1
        # QUICK SAVE STATE
        24: {}
        # QUICK LOAD STATE
        25: {}
        # CHANGE STATE SLOT
        26: {}
        # FAST FORWARD
        27: {}
        # SLOW MOTION
        28: {}
        # REWIND
        29: {}
```

**Comment by wonx** [comment]
Thanks, that was my experience as well. I had to specify which core it was all the time.

It's a pity. I just want an easy way to swap A/B and X/Y for xinput controllers in Windows.

**Comment by sliekens** [comment]
I reviewed the PR where this functionality was added and concluded that `default` should work, not sure why it doesn't.
https://github.com/rommapp/romm/pull/2360

**Comment by cocoands** [comment]
@wonx Would you mind sharing your config.yml snippet for the Xbox controllers? I’ve been pulling out my hair trying to get this to work with no luck with the mgba emulator. I don’t really see my changes taking effect either - I restart the docker container with the rewritten config, but nevertheless using the “Reset” button on the Control Settings configuration page always reverts the key bindings to the swapped layout.

_Edit: Please disregard. I was attempting to edit my config.yml on my iPad and was in tab/space formatting purgatory. When I opened up a real computer, pasted in @sliekens snippet (swapping out all emulator names and repeating as necessary). Restarted the docker and the proper controller profiles populated when I reset them._

**Comment by sliekens** [comment]
I would still like to know why "default" doesn't work. The code seems to contain support for it.

**Comment by gantoine** [comment]
> I would still like to know why "default" doesn't work. The code seems to contain support for it.

We pass the values directly to emulatorjs, if `default` isn't working it might be internal to it? But like you said the code should be correct, and I've stepped through it manually.

**Comment by cocoands** [comment]
Well, in the absence of a functioning `default`, here's another slightly more exhaustive `config.yml` excerpt for a number of additional emulators and 2 controllers:
- mgba
- gambatte
- fceumm
- nestopia
- snes9x
- pcsx_rearmed
- ppsspp

Thought sharing might save someone a few clicks if they are coming across this thread. They seem to be working for me, but it seems you'll need to manually reset the controller config on a per game level if you already started playing one.

[controls.yml](https://github.com/user-attachments/files/23837832/controls.yml)

_Disclaimer: this content was partially generated by AI_

**Comment by vladfaust** [comment]
If it may be helpful for anyone, this is my config for 8BitDo M30 connected in Android (D-Input) (Start+B) mode on MacOS for Sega Genesis (MegaDrive):

<details>

```yml
emulatorjs:
  controls:
    genesis_plus_gx:
      # | EmulatorJS | 8BitDo M30 (Start + B)    |
      # | ---------- | ------------------------- |
      # | B (0)      | B (BUTTON_2)              |
      # | Y (1)      | A (BUTTON_1)              |
      # | SELECT (2) | SELECT (LEFT_STICK)       |
      # | START (3)  | START (RIGHT_STICK)       |
      # | UP (4)     | UP (LEFT_STICK_Y:-1)      |
      # | DOWN (5)   | DOWN (LEFT_STICK_Y:+1)    |
      # | LEFT (6)   | LEFT (LEFT_STICK_X:-1)    |
      # | RIGHT (7)  | RIGHT (LEFT_STICK_X:+1)   |
      # | A (8)      | C (RIGHT_BOTTOM_SHOULDER) |
      # | X (9)      | Y (LEFT_TOP_SHOULDER)     |
      # | L (10)     | X (BUTTON_4)              |
      # | R (11)     | Z (LEFT_BOTTOM_SHOULDER)  |
      0: # Player 1
        0: # EmulatorJS: B
          value2: BUTTON_2 # 8BitDo M30: B
        1: # EmulatorJS: Y
          value2: BUTTON_1 # 8BitDo M30: A
        2: # EmulatorJS: SELECT
          value2: LEFT_STICK # 8BitDo M30: SELECT
        3: # EmulatorJS: START
          value2: RIGHT_STICK # 8BitDo M30: START
        4: # EmulatorJS: UP
          value2: LEFT_STICK_Y:-1 # 8BitDo M30: UP
        5: # EmulatorJS: DOWN
          value2: LEFT_STICK_Y:+1 # 8BitDo M30: DOWN
        6: # EmulatorJS: LEFT
          value2: LEFT_STICK_X:-1 # 8BitDo M30: LEFT
        7: # EmulatorJS: RIGHT
          value2: LEFT_STICK_X:+1 # 8BitDo M30: RIGHT
        8: # EmulatorJS: A
          value2: RIGHT_BOTTOM_SHOULDER # 8BitDo M30: C
        9: # EmulatorJS: X
          value2: LEFT_TOP_SHOULDER # 8BitDo M30: Y
        10: # EmulatorJS: L
          value2: BUTTON_4 # 8BitDo M30: X
        11: # EmulatorJS: R
          value2: LEFT_BOTTOM_SHOULDER # 8BitDo M30: Z

      1: # Player 2 (Same as Player 1)
        0: # EmulatorJS: B
          value2: BUTTON_2 # 8BitDo M30: B
        1: # EmulatorJS: Y
          value2: BUTTON_1 # 8BitDo M30: A
        2: # EmulatorJS: SELECT
          value2: LEFT_STICK # 8BitDo M30: SELECT
        3: # EmulatorJS: START
          value2: RIGHT_STICK # 8BitDo M30: START
        4: # EmulatorJS: UP
          value2: LEFT_STICK_Y:-1 # 8BitDo M30: UP
        5: # EmulatorJS: DOWN
          value2: LEFT_STICK_Y:+1 # 8BitDo M30: DOWN
        6: # EmulatorJS: LEFT
          value2: LEFT_STICK_X:-1 # 8BitDo M30: LEFT
        7: # EmulatorJS: RIGHT
          value2: LEFT_STICK_X:+1 # 8BitDo M30: RIGHT
        8: # EmulatorJS: A
          value2: RIGHT_BOTTOM_SHOULDER # 8BitDo M30: C
        9: # EmulatorJS: X
          value2: LEFT_TOP_SHOULDER # 8BitDo M30: Y
        10: # EmulatorJS: L
          value2: BUTTON_4 # 8BitDo M30: X
        11: # EmulatorJS: R
          value2: LEFT_BOTTOM_SHOULDER # 8BitDo M30: Z
```

</details>
