### ISSUE TITLE
[Bug] PC Games: ZIP and ISO downloads fail with port redirect in 3.8.0-alpha

### ISSUE THREAD

**Issue by MisterCalvin** [rommapp/romm#1644]
### RomM version
3.8.0-alpha-6 (issue present in all alpha versions 1-6)

I'm running ROMM through Docker with HAProxy handling TLS termination and Authentik for authentication

### Client Device (Desktop)

OS: Windows 10 Pro (Version 10.0.19045)
Browser: Chrome
Version: 133.0.6943.127 (Official Build) (64-bit)

(issue persists across all devices, tested with iOS as well)

### Issue Description
I've noticed that in ROMM 3.8.0-alpha (all versions 1-6), downloading zipped PC games and single-file PC games (like standalone ISOs) isn't working anymore. For context, my PC games are stored on a separate network drive but mounted into the ROMM container's library directory - a setup that has worked flawlessly for nearly 2 years. When trying to download any of these games, I get redirected to a Google Chrome error page that exposes the internal port of the container:

```
http://games.mydomain.com:8080/library/roms/win/Resident%20Evil/
```

This is happening with all my zipped and single-file PC games, but interestingly, uncompressed multi-file PC games work fine. I've tried removing and readding the affected games, as well as performing both quick and full rescans, but the issue persists. I tested this extensively, and the issue goes away completely when reverting to version 3.7.3. This only affects my PC games library - all my other platforms' zipped ROMs are working normally. Nothing in my environment has changed, and I have quite a few platforms that are all working perfectly:

```
ghost@dev-machine:/mnt/smicrotruenas-misc-roms/roms$ ls -al
total 0
drwxrwx--- 2 ghost ghost 0 Jun 12  2024 3do
drwxrwx--- 2 ghost ghost 0 Sep 28  2023 3ds
drwxrwx--- 2 ghost ghost 0 Jul 20  2024 arcade
drwxrwx--- 2 ghost ghost 0 Jun 11  2024 dreamcast
drwxrwx--- 2 ghost ghost 0 Sep 28  2023 gb
drwxrwx--- 2 ghost ghost 0 Jun 11  2024 gba
drwxrwx--- 2 ghost ghost 0 Sep 29  2023 n64
drwxrwx--- 2 ghost ghost 0 Jun 11  2024 nds
drwxrwx--- 2 ghost ghost 0 Sep 29  2023 nes
drwxrwx--- 2 ghost ghost 0 Jun 10  2024 ps
drwxrwx--- 2 ghost ghost 0 Sep 29  2023 ps2
drwxrwx--- 2 ghost ghost 0 Jul 14  2024 ps3
drwxrwx--- 2 ghost ghost 0 Dec  6 09:41 snes
drwxrwx--- 2 ghost ghost 0 Jun  9  2024 switch
drwxrwx--- 2 ghost ghost 0 Jun 28  2024 wii
drwxrwx--- 2 ghost ghost 0 Jul 17  2024 wiiu
drwxrwx--- 2 ghost ghost 0 Jun  9  2024 win
drwxrwx--- 2 ghost ghost 0 Dec  1 09:58 xbox
drwxrwx--- 2 ghost ghost 0 Jul 16  2024 xbox360
# ... and many more
```

Some of these platforms have zipped ROMs, some have a single unzipped file (such as `.chd` for PS1), and others have multi-files that continue to work perfectly - I seem to only be having an issue with the PC platform.

docker-compose.yml:
```yaml
services:
  romm:
    image: rommapp/romm:${ROMM_IMAGE:-latest}
    container_name: romm
    environment:
      TZ: ${TZ}
      DB_HOST: romm-db
      DB_NAME: romm
      DB_USER: ${ROMM_DB_USER}
      DB_PASSWD: ${ROMM_DB_PASSWD}
      ROMM_AUTH_SECRET_KEY: ${ROMM_AUTH_SECRET_KEY}
      IGDB_CLIENT_ID: ${ROMM_IGDB_CLIENT_ID}
      IGDB_CLIENT_SECRET: ${ROMM_IGDB_CLIENT_SECRET}
      MOBYGAMES_API_KEY: ${ROMM_MOBYGAMES_API_KEY}
      STEAMGRIDDB_API_KEY: ${ROMM_STEAMGRIDDB_API_KEY}
      SCREENSCRAPER_USER: ${ROMM_SCREENSCRAPER_USER}
      SCREENSCRAPER_PASSWORD: ${ROMM_SCREENSCRAPER_PASSWORD}
      DISABLE_DOWNLOAD_ENDPOINT_AUTH: true
      OIDC_ENABLED: ${OIDC_ENABLED}
      OIDC_PROVIDER: ${OIDC_PROVIDER}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_REDIRECT_URI: ${OIDC_REDIRECT_URI}
      OIDC_SERVER_APPLICATION_URL: ${OIDC_SERVER_APPLICATION_URL}
      DISABLE_USERPASS_LOGIN: true
    volumes:
      - romm_resources:/romm/resources
      - romm_redis_data:/redis-data
      - /mnt/smicrotruenas-misc-roms/:/romm/library
      - /mnt/smicrotruenas-nvme/Games-Test:/romm/library/roms/win
      - ./assets:/romm/assets
      - ./config:/romm/config
    ports:
      - 9800:8080
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true
    logging:
      driver: gelf
      options:
        gelf-address: ${ROMM_SYSLOG_ADDRESS}
    restart: unless-stopped
```

config.yml:
```yaml
exclude:
  platforms:
  - romm
  roms:
    multi_file:
      names:
      - my_multi_file_game
      - DLC
      - escape
      parts:
        extensions:
        - txt
        names:
        - data.xml
        - ._*
        - manifest.txt
    single_file:
      extensions:
      - xml
      - swf
      names:
      - info.txt
      - ._*
      - '*.nfo'
filesystem:
  roms_folder: roms
system:
  platforms:
    dreamcast: dc
    gbc: gbc
    ngc: ngc
    ps4: ps4--1
  versions:
    naomi: arcade
```

### What's Working vs Not Working
Here's a log from a successful download of an unzipped game (Vyruz):
```
INFO:     [RomM][rom][2025-02-21 13:29:15] User Ghost is downloading Vyruz - Destruction of the Untel Empire
10.10.0.233:0 - "GET /api/roms/16432/content/Vyruz%20-%20Destruction%20of%20the%20Untel%20Empire HTTP/1.0" 200
INFO:     [nginx][2025-02-21 ]  127.0.0.1 - - "GET /library/roms/win/Vyruz%20-%20Destruction%20of%20the%20Untel%20Empire/VYRUZ.bin HTTP/1.0" 200 517 "-" "-" rt=0.000 uct="-" uht="-" urt="-"
INFO:     [nginx][2025-02-21 ]  127.0.0.1 - - "GET /library/roms/win/Vyruz%20-%20Destruction%20of%20the%20Untel%20Empire/VYRUZ.cue HTTP/1.0" 200 517 "-" "-" rt=0.000 uct="-" uht="-" urt="-"
INFO:     [nginx][2025-02-21 ]  127.0.0.1 - - "GET /library/roms/win/Vyruz%20-%20Destruction%20of%20the%20Untel%20Empire/unecm.bat HTTP/1.0" 200 76 "-" "-" rt=0.000 uct="-" uht="-" urt="-"
INFO:     [nginx][2025-02-21 ]  127.0.0.1 - - "GET /library/roms/win/Vyruz%20-%20Destruction%20of%20the%20Untel%20Empire/unecm.exe HTTP/1.0" 200 7680 "-" "-" rt=0.000 uct="-" uht="-" urt="-"
INFO:     [nginx][2025-02-21 ]  10.101.0.254 - - "GET /api/roms/16432/content/Vyruz%20-%20Destruction%20of%20the%20Untel%20Empire? HTTP/1.1" 200 9575 "https://games.mydomain.com/rom/16432" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36" rt=0.089 uct="0.000" uht="0.075" urt="0.076"
```

And here's what happens with a zipped PC game (Witchaven):
```
INFO:     [RomM][rom][2025-02-21 13:29:34] User Ghost is downloading Witchaven
10.10.0.233:0 - "GET /api/roms/16431/content/Witchaven HTTP/1.0" 200
INFO:     [nginx][2025-02-21 ]  10.101.0.254 - - "GET /api/roms/16431/content/Witchaven? HTTP/1.1" 301 169 "https://games.mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36" rt=0.038 uct="0.000" uht="0.038" urt="0.038"
```

I've verified that the files are mounted correctly in the container:
```
0e7395541dc0:/romm/library/roms/win# ls -al Resident\ Evil/ 4x4\ EVO/ Witchaven/ Vyruz\ -\ Destruction\ of\ the\ Untel\ Empire/
4x4 EVO/:
total 137989
drwxrwx---    2 romm     romm             0 Aug 13  2024 .
drwxrwx---    2 romm     romm             0 Feb 21 13:27 ..
-rw-rw-r--    1 romm     romm     142667776 Feb  6  2011 4x4 Evolution.iso

Resident Evil/:
total 549177
drwxrwx---    2 romm     romm             0 Jan 12 22:25 .
drwxrwx---    2 romm     romm             0 Feb 21 13:27 ..
-rw-rw-r--    1 romm     romm     562282585 Jan 12 22:24 Resident Evil 1.zip

Witchaven/:
total 277789
drwxrwx---    2 romm     romm             0 Jan 12 22:46 .
drwxrwx---    2 romm     romm             0 Feb 21 13:27 ..
-rw-rw-r--    1 romm     romm     284582402 Jan 12 20:03 Witchaven.zip

Vyruz - Destruction of the Untel Empire/:
total 18
drwxrwx---    2 romm     romm             0 Feb 21 13:28 .
drwxrwx---    2 romm     romm             0 Feb 21 13:27 ..
-rw-rw-r--    1 romm     romm           517 Aug  8  2008 VYRUZ.bin
-rw-rw-r--    1 romm     romm           517 Aug  8  2008 VYRUZ.cue
-rw-rw-r--    1 romm     romm            76 Aug 22  2008 unecm.bat
-rw-rw-r--    1 romm     romm          7680 Jun 16  2002 unecm.exe
```

### To Reproduce
1. Try downloading any zipped PC game or single-file PC game (`.iso` or other)
2. Watch it fail with a redirect to the internal port URL
3. Try downloading an unzipped PC game with multiple files - it works fine
4. Roll back to 3.7.3 - everything works again

Let me know if you need any additional information!
