### ISSUE TITLE
[Bug] Save State no longer seems to update

### ISSUE THREAD

**Issue by murrple-1** [rommapp/romm#1718]
**RomM version**
3.8.0

**Describe the bug**
The previous save state behaviour seems to be broken.

**To Reproduce**

1. Open a game with auto save state (save state created in RomM v3.7)
2. Game opens at expected state
3. Play
4. Press the "Save State" floppy-disk icon (red text "Save Saved to Browser" appears in upper-left - I think it used to say "Save Saved to ROMM" in v3.7, but don't mark me on that)
5. Exit Game
6. Return to game, open with auto save state
5. Progress from previous play session lost, return to save state as it was initially

Video:

https://github.com/user-attachments/assets/b80f50c2-c401-4d54-a5c2-ec5b91861871

**Expected behavior**
Previously, the "Save State" icon would save the state to the server, and you could pick up where you left off from any device.

**Screenshots**

**Desktop:**

- OS: Linux Mint
- Browser Firefox
- Version 136

**Docker Compose Config:**

```yaml
services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    environment:
      - DB_HOST=romm-db
      - DB_NAME=romm
      - DB_USER=romm-user
      - DB_PASSWD=<redacted>
      - ROMM_AUTH_SECRET_KEY=<redacted>
      - IGDB_CLIENT_ID=<redacted>
      - IGDB_CLIENT_SECRET=<redacted>
    volumes:
      - romm_resources:/romm/resources/
      - romm_redis_data:/redis-data/
      - /home/<redacted>/romm/library/:/romm/library/ # Your game library. Check https://github.com/rommapp/romm?tab=readme-ov-file#folder-structure for more details.
      - /home/<redacted>/romm/assets/:/romm/assets/
      - /home/<redacted>/romm/config/:/romm/config/
    ports:
      - 8041:8080
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true
  romm-db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=<redacted>
      - MARIADB_DATABASE=romm
      - MARIADB_USER=romm-user
      - MARIADB_PASSWORD=<redacted>
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  romm_resources:
  romm_redis_data:
```

**Additional context**
