### ISSUE TITLE
[Bug] Authelia OIDC SSO error 'Email is missing from token'

### ISSUE THREAD

**Issue by unsubscrieb** [rommapp/romm#1809]
**RomM version**
3.8.1

**Describe the bug**
When attempting to authenticate via Authelia as OIDC SSO provider, callback fails with error in title
{"detail":"Email is missing from token."}

**To Reproduce**

1. Set up Authelia client and RomM OIDC provider as per instructions https://github.com/rommapp/romm/wiki/OIDC-Setup-With-Authelia
2. Restart containers
3. Click `Login with Authelia` button, `Approve` on Authelia page, see error

**Expected behavior**
Login proceeds successfully.

**Desktop (please complete the following information):**

- OS: Win11
- Browser: Firefox
- Version: 136.0.4

**Smartphone (please complete the following information):**

**Additional context**
Authelia configuration.yml
```
      - client_id: '[redacted]'
        client_name: 'RomM'
        client_secret: {{ secret "/secrets/oidc/clients/romm/client_digest" | mindent 0 "|" | msquote }}
        public: false
        authorization_policy: 'one-factor'
        grant_types:
          - 'authorization_code'
        redirect_uris:
          - "https://[URL]/api/oauth/openid"
        scopes:
          - 'openid'
          - 'email'
          - 'profile'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
```

RomM docker .env
```
OIDC_ENABLED="true"
OIDC_PROVIDER="authelia"
OIDC_CLIENT_ID="[redacted]"
OIDC_CLIENT_SECRET="[redacted]"
OIDC_REDIRECT_URI="https://[URL]/api/oauth/openid"
OIDC_SERVER_APPLICATION_URL="https://[URL]"
```
