### ISSUE TITLE
Emulation on NEOGEO MVS doesn´t work

### ISSUE THREAD

**Issue by BRaSSaS** [rommapp/romm#1819]
**RomM version**
3.8.2

**Describe the bug**
A setup a library/roms/neogeomvs roms folder with some test roms. But dont work, dont load de bios and gime me a FBNeo Error at loading this ROMS inside bios file.
I test to put the neogeo.zip on the path /library/bios/neogeomvs, inside a zip file, outside and also with de inside the game rom zip. But nothing works.

**Screenshots**

![Image](https://github.com/user-attachments/assets/ec0d2b69-bdb5-40be-bcee-89e12967591c)

**Comment by BRaSSaS** [comment]
But if i put the same rom in /library/roms/arcade works with the option Core: mame2023

**Comment by niko44** [comment]
I'm also having the same issue.
My config : 
Romm deployed in Docker  with this extract of docker-compose : 
```
    romm:
        image: rommapp/romm:latest
        container_name: romm
        restart: unless-stopped
        user: "1030:100"
        environment:
            - DB_HOST=romm-db
            - DB_NAME=romm
            - DB_USER=romm-user
            - DB_PASSWD=#############
            - ROMM_AUTH_SECRET_KEY=#############
            - IGDB_CLIENT_ID=#############
            - IGDB_CLIENT_SECRET=#############
            - MOBYGAMES_API_KEY=#############
            - STEAMGRIDDB_API_KEY=#############
            - SCREENSCRAPER_USER=#############
            - SCREENSCRAPER_PASSWORD=#############
            - RETROACHIEVEMENTS_API_KEY=#############
            - LOGLEVEL=INFO
        volumes:
            - /volume3/recalbox:/romm/library
            - /volume3/docker/niko44/emulatorweb/romm/resources:/romm/resources
            - /volume3/docker/niko44/emulatorweb/romm/redis:/redis-data
            - /volume3/docker/niko44/emulatorweb/romm/assets:/romm/assets
            - /volume3/docker/niko44/emulatorweb/romm/config:/romm/config
        ports:
            - 4080:8080
        depends_on:
            romm-db:
              condition: service_healthy
```
As you can see, my library is shared between my Recalbox and Romm. All files are accessible by the same user (ie. uid=1030) and have the same rights (rw). So it's not a permission problem.

Like @BRaSSaS ,I have tried to put my neogeo.zip file in : 
-  /volume3/recalbox/fbneo/
-  /volume3/recalbox/fbneo/bios
-  /volume3/recalbox/neogeo/
-  /volume3/recalbox/neogeo/bios
-  /volume3/recalbox/bios

I also have tried unzip the neogeo.zip **before** starting the container in all those directories, but still the same error...

For information, my neogeo.zip is not corrupt and all files mentioned by the screen are in the archive et have the correct CRC : 

![Image](https://github.com/user-attachments/assets/1c0209c9-d54d-47a6-85d5-d6ea917d2f1e)

I have no error with other platform, it's only with NeoGeo.
