### ISSUE TITLE
[Bug] Searching IGDB/Screenscraper only works by ID number

### ISSUE THREAD

**Issue by BlueBackbite** [rommapp/romm#1922]
**RomM version**
3.9.0

**Describe the bug**
Upon fresh creation of 3.9.0 docker compose, on x86_64 platforms, RomM is able to search for ROM matches by ID number. This is only able to match titles with their ID number, rather than name while manually searching.

**To Reproduce**
See if this issue is reproducible with this docker compose:

```yaml
volumes:
  mysql_data:
  romm_resources:
  romm_redis_data:

services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    environment:
      - DB_HOST=romm-db
      - DB_NAME=romm
      - DB_USER=romm-user
      - DB_PASSWD=redacted
      - ROMM_AUTH_SECRET_KEY=redacted
      - IGDB_CLIENT_ID=redacted
      - IGDB_CLIENT_SECRET=redacted
      #- MOBYGAMES_API_KEY= # https://docs.romm.app/latest/Getting-Started/Generate-API-Keys/#mobygames
      #- STEAMGRIDDB_API_KEY= # https://docs.romm.app/latest/Getting-Started/Generate-API-Keys/#steamgriddb
      - SCREENSCRAPER_USER=redacted
      - SCREENSCRAPER_PASSWORD=redacted
    volumes:
      - romm_resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - romm_redis_data:/redis-data # Cached data for background tasks
      - /mnt/outerstation_dl/Software - games/_CONSOLE_ROMS:/romm/library # Your game library. Check https://github.com/rommapp/romm?tab=readme-ov-file#folder-structure for more details.
      - /mnt/outerstation_dl/Software - games/_romm_assets:/romm/assets # Uploaded saves, states, etc.
      - /mnt/outerstation_dl/Software - games/_romm_config:/romm/config # Path where config.yml is stored
    ports:
      - 806:8080
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=redacted
      - MARIADB_DATABASE=romm
      - MARIADB_USER=romm-user
      - MARIADB_PASSWORD=redacted
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
```

**Expected behavior**
The RomM app is able to search 3rd party APIs via title name.
The issue persists after running `docker compose down -v` and `docker compose up -d`

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11 24H2
- Browser: Opera GX + tested in MS Edge
- Version: Chromium version:133.0.6943.143

**Smartphone (please complete the following information):**

N/A

**Additional context**
This docker server was having issues with DNS resolution at one point in time recently, but that issue was fixed and doesn't explain why searching by ID works.

Additionally, every .ico file for each system returns as a 404; library, assets, and config are stored on a CIFS share and have the following permissions:
```sh
$ docker exec romm ls -alh /romm/library
total 4K
drwxrwxr-x    2 romm     1003           0 May 29 03:46 .
drwxr-xr-x    1 romm     romm        4.0K May 29 03:51 ..
drwxrwxr-x    2 romm     1003           0 Oct 25  2018 Atari 2600
drwxrwxr-x    2 romm     1003           0 May 29 02:14 Game Boy Color
...
```
I see the config.yml get created, but nothing seems to show up in the assets folder.
