### ISSUE TITLE
[Bug] Scan didn't get the roms but the folders

### ISSUE THREAD

**Issue by update-freak** [rommapp/romm#2031]
**RomM version**
v3.10.2

**Describe the bug**
I have the problem that with the scan I only get the platform folders but not the games in it. (see screenshots).
Also the info "Please select at least one metadata source if you want to enrich your library with artwork and metadata" is not good visible with light design.

**To Reproduce**
1. Scan in the settings

**Expected behavior**
I get the roms in the platform folders

**Screenshots**

![Image](https://github.com/user-attachments/assets/425139bf-4f78-4094-82c7-58497308389f)

![Image](https://github.com/user-attachments/assets/3b0c4244-49a7-4c05-a182-f17cc5edab5c)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Firefox
- Version: 140.0.2

**docker compose (I removed the scretkey)**

```
services:
  romm:
    image: rommapp/romm:latest
    container_name: RomM
    restart: always
    environment:
      - TZ=Europe/Berlin
      - DB_HOST=romm-db
      - DB_NAME=romm # Should match MARIADB_DATABASE in mariadb
      - DB_USER=romm-user # Should match MARIADB_USER in mariadb
      - DB_PASSWD=romm-pass # Should match MARIADB_PASSWORD in mariadb
      - ROMM_AUTH_SECRET_KEY= SECRETKEY # Generate a key with `openssl rand -hex 32`
    volumes:
      - /volume1/docker/romm/resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - /volume1/docker/romm/redis-data:/redis-data # Cached data for background tasks
      - /volume1/Installationsdateien/Spiele/Nintendo/roms:/romm/library # Your game library. Check https://github.com/rommapp/romm?tab=readme-ov-file#folder-structure for more details.
      - /volume1/docker/romm/assets:/romm/assets # Uploaded saves, states, etc.
    ports:
      - 1037:8080
    depends_on:
      - romm-db

  romm-db:
    image: mariadb:latest
    container_name: RomM-db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=romm-root # Use a unique, secure password
      - MARIADB_DATABASE=romm
      - MARIADB_USER=romm-user
      - MARIADB_PASSWORD=romm-pass
    volumes:
      - /volume1/docker/romm/mysql_data:/var/lib/mysql
```
