### ISSUE TITLE
v3.0.2 release notes issue

### ISSUE THREAD

**Issue by lnlyssg** [rommapp/romm#755]
A minor problem but the release notes for v3.0.2 say "Updated [docker-compose.example.yml file](https://github.com/rommapp/romm/blob/3.0.1/examples/docker-compose.example.yml) to match new dockerhub rommapp organization" but the linked file is the v3.0.1 version so still contains zurdi15/romm

**Comment by gantoine** [comment]
Fixed, thank you! You should use 3.0.3 however since 3.0.2 has a critical bug.

**Comment by lnlyssg** [comment]
Yup it was when I was updating again to 3.0.3 that I spotted the issue. Will the example docker-compose file be updated to include the `user:uid:gid` entry or is this just a temporary measure?

**Comment by gantoine** [comment]
> Will the example docker-compose file be updated to include the user:uid:gid entry or is this just a temporary measure?

So uh turns out that still doesn't work in 3.0.3. I've been trying to getting working all evening but with no luck. There's a catch-22 with folder permissions on build vs user ID on run. If you're familiar with this stuff I could really use the help!

**Comment by lnlyssg** [comment]
It seems to be working Ok for me, I was getting permissions errors on the log file e.g. `PermissionError: [Errno 13] Permission denied: '/romm/logs/20240325_170108.log'` And it just kept looping so I then specified the user entry like the below dummy example and now everything looks to be working OK:

```
services:
  romm:
    image: rommapp/romm:3.0.3
    container_name: romm
    restart: unless-stopped
    user: 123:456
    environment:
      - DB_HOST=romm-db
      ...
 ```
