### ISSUE TITLE
[Bug] Romm does not start after the latest update

### ISSUE THREAD

**Issue by Dreadlocke12** [rommapp/romm#758]
**RomM version**
Latest available version installed at 25.03
**Describe the bug**
After the recent update ( in my case done vie watchtower) romm is not starting anymore evwn it says it is ready in portainer.

Running 

sudo docker logs romm

Shows

/Init: line 105: PUID: unbound variable

**Comment by zurdi15** [comment]
Hi! from which repository you pulled the image? We recently moved to a new location (rommapp)[https://hub.docker.com/layers/rommapp/romm].

That bug is fixed in the [3.0.3][https://hub.docker.com/layers/rommapp/romm/3.0.3/images/sha256-46a9bf187572fb38271c05a6a8ab5cbc3594201ae576bf1defce126af26caffa?context=repo] version in that new location

**Comment by Dreadlocke12** [comment]
Ok i changed it to rommapp/romm but it still does not work and shows me 


PermissionError: [Errno 13] Permission denied: '/romm/logs/20240326_112216.log'
ERROR:    [init][2024-03-26 11:22:16] Something went horribly wrong with our database
Traceback (most recent call last):
  File "/backend/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/backend/lib/python3.11/site-packages/alembic/config.py", line 641, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/backend/lib/python3.11/site-packages/alembic/config.py", line 631, in main
    self.run_cmd(cfg, options)
  File "/backend/lib/python3.11/site-packages/alembic/config.py", line 608, in run_cmd
    fn(
  File "/backend/lib/python3.11/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/backend/lib/python3.11/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/backend/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/backend/alembic/env.py", line 6, in <module>
    from config.config_manager import ConfigManager
  File "/backend/config/config_manager.py", line 22, in <module>
    from logger.logger import log
  File "/backend/logger/logger.py", line 28, in <module>
    file_handler = logging.FileHandler(logs_file)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



When trying to collect display the logs. I would not know how to adjust the permissions though.

**Comment by gantoine** [comment]
Can you try stopping romm, rm the container, delete any old romm images from docker, then in your docker-compose pin it to 3.0.3, and start it again? You may have an old version cached.

**Comment by Dreadlocke12** [comment]
Removed everything all Containers images and as well all folders created and tried with latest as well with 3.0.3 but the result is the same

**Comment by gantoine** [comment]
can you post your docker-compose? and what does your setup look like (os, etc)?

**Comment by Dreadlocke12** [comment]
It runs on an lxc container and os is ubuntu

**Comment by gantoine** [comment]
ok so first off your compose it fairly out of date, you should adapt it to the latest example, which is much more simplified https://github.com/rommapp/romm/blob/3.0.3/examples/docker-compose.example.yml

what are the permissions of the `/home/admin/docker/romM/logs/` folder?

**Comment by zurdi15** [comment]
>  - CLIENT_ID=***
> - CLIENT_SECRET=***

I edited your comment because you had your IGDB credentials in plain text

**Comment by Dreadlocke12** [comment]
The permissions are set to root:root

**Comment by gantoine** [comment]
Ok that might be why, you should loosen the perms a bit, or just don't mount that volume if you don't need to access logs regularly.

**Comment by Dreadlocke12** [comment]
Ok so i checked it with the suggested compose file and adjusted the permissions like this 

drwxr-xrwx 6 admin admin 4096 Mar 26 15:01 .
drwxr-xr-x 4 root  root  4096 Mar 26 13:19 ..
drwxr-xrwx 2 admin admin 4096 Mar 26 13:20 config.yml
drwxr-xrwx 2 admin admin 4096 Mar 26 13:20 database
-rw-r--rwx 1 admin admin 1699 Mar 26 15:01 docker-compose.yml
drwxr-xrwx 2 root  root  4096 Mar 26 15:02 logs
drwxr-xrwx 2 admin admin 4096 Mar 26 13:20 resources


so the logs folder permissions are gone but now it seems some issue with the db access: 

mariadb.OperationalError: Access denied for user 'admin'@'172.18.0.3' (using password: YES)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/backend/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/backend/lib/python3.11/site-packages/alembic/config.py", line 641, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/backend/lib/python3.11/site-packages/alembic/config.py", line 631, in main
    self.run_cmd(cfg, options)
  File "/backend/lib/python3.11/site-packages/alembic/config.py", line 608, in run_cmd
    fn(
  File "/backend/lib/python3.11/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/backend/lib/python3.11/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/backend/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/backend/alembic/env.py", line 86, in <module>
    run_migrations_online()
  File "/backend/alembic/env.py", line 71, in run_migrations_online
    with engine.connect() as connection:
         ^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3279, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/backend/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2443, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/backend/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3303, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "/backend/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/backend/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/backend/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
  File "/backend/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/backend/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/mariadb/__init__.py", line 146, in connect
    connection = connectionclass(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/mariadb/connections.py", line 85, in __init__
    super().__init__(*args, **kwargs)
sqlalchemy.exc.OperationalError: (mariadb.OperationalError) Access denied for user 'admin'@'172.18.0.3' (using password: YES)
(Background on this error at: https://sqlalche.me/e/20/e3q8)
ERROR:    [init][2024-03-26 15:02:46] Something went horribly wrong with our database



I checked it a few times and the password is exactly the same in DB_PASSWD as in MYSQL_PASSWORD. Same as the username has been adjusted.

**Comment by gantoine** [comment]
At this point I'd recommend reverting to 3.0.1 until 3.1 is released.

**Comment by sondregronas** [comment]
Looks like the `romm` user inside the container is missing a lot of permissions. The container won't start with the logs folder as a mapped volume, and it doesn't seem to have permission interact with the docker volumes either.

Logs from a fresh install (pruned all volumes etc)
```
INFO:     [RomM][2024-03-26 17:56:22] Connecting to redis...
INFO:     [RomM][2024-03-26 17:56:23] Twitch token fetched!
INFO:     [RomM][2024-03-26 17:57:47] Found 21 platforms in file system
INFO:     [RomM][2024-03-26 17:57:47] · n64
INFO:     [RomM][2024-03-26 17:57:48]   Identified as Nintendo 64 🎮
INFO:     [RomM][2024-03-26 17:57:48]   42 roms found
INFO:     [RomM][2024-03-26 17:57:48]    · Super Mario 64
INFO:     [RomM][2024-03-26 17:57:49]      Identified as Super Mario 64 👾
ERROR:    [RomM][2024-03-26 17:57:49] [Errno 13] Permission denied: '/romm/resources/n64'
```
The scan ends here

`compose.yml`
```yaml
volumes:
  mysql_data:
  romm_resources:
  romm_redis_data:
services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    environment:
      - DB_HOST=romm_db
      - DB_PORT=3306
      - DB_USER=<redacted>
      - DB_NAME=<redacted>
      - DB_PASSWD=<redacted>
      # Metadata
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET}
      # Cron jobs
      - ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=true
      - RESCAN_ON_FILESYSTEM_CHANGE_DELAY=5
      - ENABLE_SCHEDULED_RESCAN=true
      - SCHEDULED_RESCAN_CRON=0 3 * * *
      - ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB=true
      - SCHEDULED_UPDATE_SWITCH_TITLEDB_CRON=0 4 * * *
      - ENABLE_SCHEDULED_UPDATE_MAME_XML=true
      - SCHEDULED_UPDATE_MAME_XML_CRON=0 5 * * *
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY}
    volumes:
      - romm_resources:/romm/resources
      - romm_redis_data:/redis-data
      - "/mnt/NAS-Games/:/romm/library:ro"
      - "./assets:/romm/assets"
      - "./config:/romm/config"
#      - "./logs:/romm/logs"
    ports:
      - 8080:8080
    restart: "unless-stopped"
    depends_on:
      - romm_db
  romm_db:
    image: mariadb:latest
    container_name: romm_db
    environment:
      - MYSQL_ROOT_PASSWORD=<redacted>
      - MYSQL_DATABASE=<redacted>
      - MYSQL_USER=<redacted>
      - MYSQL_PASSWORD=<redacted>
    volumes:
      - mysql_data:/var/lib/mysql
    restart: "unless-stopped"
```

```bash
c15264a4d0b2:/romm$ whoami
romm
c15264a4d0b2:/romm$ touch assets/test
touch: assets/test: Permission denied
c15264a4d0b2:/romm$ ls -la
total 24
drwxrwxrwx    1 romm     romm          4096 Mar 26 17:55 .
drwxr-xr-x    1 root     root          4096 Mar 26 17:55 ..
drwxr-xr-x    2 root     root          4096 Mar 26 17:55 assets
drwxr-xr-x    2 root     root          4096 Mar  9 14:04 config
drwxrwxrwx    2 romm     romm             0 Mar 20 13:30 library
drwxr-xr-x    2 romm     romm          4096 Mar 26 17:56 logs
drwxr-xr-x    2 root     root          4096 Mar 26 17:55 resources
```
