### ISSUE TITLE
[BUG] App crashes when i scan library

### ISSUE THREAD

**Issue by eimparas** [rommapp/romm#772]
**RomM version**
RomM 3.0.3

**Describe the bug**
Did a clean install of RomM on my macine , using the supplied compose file tweeked to my needs 
```
version: "3"

volumes:
  mysql_data:
  romm_resources:
  romm_redis_data:

services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    environment:
      - DB_HOST=romm-db
      - DB_NAME=romm # Should match MYSQL_DATABASE in mariadb
      - DB_USER=romm-user # Should match MYSQL_USER in mariadb
      - DB_PASSWD=p@ssw0rd  # Should match MYSQL_PASSWORD in mariadb
      - IGDB_CLIENT_ID=j  # Generate an ID and SECRET in IGDB
      - IGDB_CLIENT_SECRET=t  # https://api-docs.igdb.com/#account-creation
      - MOBYGAMES_API_KEY=moby   # https://www.mobygames.com/info/api/
      - ROMM_AUTH_SECRET_KEY=  # Generate a key with `openssl rand -hex 32`
      - ROMM_AUTH_USERNAME=admin
      - ROMM_AUTH_PASSWORD=admin # default: admin
    volumes:
      - /DockerData/RomManager/resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - /DockerData/RomManager/redis_data:/redis-data # Cached data for background tasks
      - /mnt/GameVault/TempRoms:/romm/library/roms # Your game library
      - /DockerData/RomManager/assets:/romm/assets # Uploaded saves, states, etc.
      - /DockerData/RomManager/config:/romm/config # [Optional] Path where config.yml is stored
    ports:
      - 84:8080
    depends_on:
      - romm-db

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=r00tP@as # Use a unique, secure password
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - /DockerData/RomManager/mysql_data:/var/lib/mysql
```

[config.txt](https://github.com/rommapp/romm/files/14807338/config.txt)

wrote this config file and proccedd to scan my library (about 250GB of roms if this matters) 
the web interface would be stuck on the loading and be inresponsive ... i did a `ctrl`+`R` and i got back to the library , there were added 2-3 platforms and i was able to click on them , but they would all say : ![image](https://github.com/rommapp/romm/assets/20401903/7f0a420a-bc1f-403a-b83b-7c6a6e931116) . IF i went manualy to scan for the game on IGDB for example it would find it or i could import it via the IGDB id .. 

**To Reproduce**

After finishing making the docker mounts, folder structure tweeks on the config.yaml 

1. Go to 'Library'
2. Check `Complete rescan` , `Rescan Unidentifed`,  Click on `SCAN'
3. hang tight till it becomes unresponsive. 
4. Observe browser logs for erros like : 403 forbiden 

**Expected behavior**
Scan the game library, import it , import details from IGDB
**Screenshots**
![image](https://github.com/rommapp/romm/assets/20401903/fa2239f0-fac3-4ac7-833c-49baa2910b74)

**Desktop (please complete the following information):**
 - OS:  Microsoft Windows 10 Pro 
 - OS Version:                10.0.19045 N/A Build 19045
 - Browser  Google Chrome	123.0.6312.86 (Official Build) (64-bit) (cohort: Stable) 
Revision	9b72c47a053648d405376c5cf07999ed626728da-refs/branch-heads/ 
OS	Windows 10 Version 22H2 (Build 19045.4170)
JavaScript	V8 12.3.219.14
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

** Server ** 
-  docker version
Client:
 Version:           20.10.5+dfsg1
 API version:       1.41
 Go version:        go1.15.15
 Git commit:        55c4c88
 Built:             Mon May 30 18:34:49 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.5+dfsg1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.15
  Git commit:       363e9a8
  Built:            Mon May 30 18:34:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:         ` 1.4.13~ds1`
  GitCommit:        `1.4.13~ds1-1~deb11u4`
 runc:
  Version:         ` 1.0.0~rc93+ds1`
  GitCommit:        `1.0.0~rc93+ds1-5+deb11u3`
 docker-init:
  Version:          0.19.0
  GitCommit: 
runnin on debian 12

**Additional context**

[_romm_logs.txt](https://github.com/rommapp/romm/files/14807329/_romm_logs.txt)
