### ISSUE TITLE
[Bug] 3.2.0-rc.1 bios do not respect exclusions in config.yml

### ISSUE THREAD

**Issue by jiannazzone** [rommapp/romm#849]
**RomM version**
3.2.0-rc.1

**Describe the bug**
When scanning for bios files, my exclusion rules are not applied. For example, `.DS_Store` is picked up, even when I add a matching `bios` section in config.yml.

**To Reproduce**
1. Add exclusion rule to config.yml (see below)
2. Start docker logs
3. Initiate platform scan
4. Observe that files are catalogued even when they should be excluded

```
bios:
    single_file:
      names:
        - '._*'
        - '.DS_Store'
```

The ._gba_bios.bin file should be ignored.
![gba-bios-screen](https://github.com/rommapp/romm/assets/46025473/28d9f50e-2c3f-478d-b635-00b725b7ae19)
