### ISSUE TITLE
[Bug] installation failure

### ISSUE THREAD

**Issue by iroQuai** [rommapp/romm#884]
**RomM version**
I'm using the docker compose example from [here](https://github.com/rommapp/romm/blob/release/examples/docker-compose.example.yml). 

**Describe the bug**
Romm isn't starting properly. 

**To Reproduce**
This is my compose data
```
version: "3"
volumes:
  mysql_data: 
  romm_resources: 
  romm_redis_data: 
services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    environment:
      - DB_HOST=romm-db
      - DB_NAME=romm # Should match MYSQL_DATABASE in mariadb
      - DB_USER=romm-user # Should match MYSQL_USER in mariadb
      - DB_PASSWD=${ROMM_DB_PW} # Should match MYSQL_PASSWORD in mariadb
      - IGDB_CLIENT_ID=${IGDB_ID} # Generate an ID and SECRET in IGDB
      - IGDB_CLIENT_SECRET=${IGDB_SECRET} # https://api-docs.igdb.com/#account-creation
      - MOBYGAMES_API_KEY=${MOBY_API} # https://www.mobygames.com/info/api/
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_KEY} # Generate a key with `openssl rand -hex 32`
      - ROMM_AUTH_USERNAME=stijn
      - ROMM_AUTH_PASSWORD=${ROMM_PW} # default: admin
    volumes:
      - romm_resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - romm_redis_data:/redis-data # Cached data for background tasks
      - /volume1/gaming/roms:/romm/library # Your game library
      - ./assets:/romm/assets # Uploaded saves, states, etc.
      - ./config:/romm/config # Path where config.yml is stored
    ports:
      - 7777:8080
    depends_on:
      - romm-db
  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_root_pw123 # Use a unique, secure password
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=${ROMM_DB_PW}
    volumes:
      - mysql_data:/var/lib/mysql
networks: {}
```
I have an .env file with all mentioned ${STRINGS} filled in.

I use dockge to manage my stacks. Through dockge I created a stack (=folder) called "romm" and added above compose file and matching .env file. I also added a /config/ and an /assets/ folder in that /romm/ folder.

I pressed "start" which is the dockge equivalent of "docker compose up".

The mariaDB container just runs. The Romm container runs, but isn't visible.it exits with code 1, mentioning "something went horribly wrong with our database" and also something about sqlalchemy.exc.operationalError  "host 192.168.112.3 is not allowed to connect to this MariaDB server.

After some time the Romm container tries to restart, over and over. Untill I stop it. 

If needed I can try and discover how to get the full logs (probably not that hard just never did it before)

**Expected behavior**
I expected both the mariadb container as the romm container to be created and running. I expected to be able to visit romm at the specified port

**Additional context**
I'm on Synology DS220+ if that matters?
I've manage around 10 other stacks that work fine this way. If it matters I can spin up the compose file via cli once too (but I can't believe that would matter)

**Comment by gantoine** [comment]
> host 192.168.112.3 is not allowed to connect to this MariaDB server.

for some reason mariadb is rejecting connections from romm/the localhost. i asked chatgpt and it said to do this:

Configure MariaDB to Listen on All IP Addresses:
You need to modify the MariaDB configuration to bind to all IP addresses. This can be done by creating a custom configuration file.

Create a custom configuration file my_custom.cnf with the following content:

```
[mysqld]
bind-address = 0.0.0.0
```

Then, mount this configuration file in your docker-compose.yml:

```
services:
  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_root_pw123 # Use a unique, secure password
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=${ROMM_DB_PW}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf  # Mount the custom configuration file
    ports:
      - "3306:3306"  # Expose port 3306
```

Grant User Permissions:
Access the MariaDB container and grant the necessary permissions to the user from the specified IP address.

```
# Access the MariaDB container
docker exec -it romm-db bash

# Access MariaDB as root
mysql -u root -p
```

Inside the MariaDB shell, grant the necessary permissions:

```
GRANT ALL PRIVILEGES ON *.romm TO 'romm-user'@'192.168.112.3' IDENTIFIED BY 'your_password';
FLUSH PRIVILEGES;
```
